version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20

jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      # - run:
      #     name: Test the application
      #     command: yarn test
      # - run:
      #     name: Setup Platform API url
      #     command: sh ./scripts/setup_dotenv.sh
      - run:
          name: Build the application
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - package.json
            - node_modules
            - src
            - build
  deploy-to-s3:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup
      - run:
          name: Upload file to S3
          command: aws s3 sync build/ s3://skand-admin-dashboard --acl public-read
workflows:
    build-and-test:
      jobs:
        - build-and-test:
            context: Skand-S3
        - deploy-to-s3:
            context: Skand-S3
            requires:
              - build-and-test
            filters:
              branches:
                only: master

# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
# jobs:
#   build-and-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: npm install
#             - run: npm test
#             - run: npm run deploy
# workflows:
#     build-and-test:
#       jobs:
#         - build-and-test

# defaults: &defaults
#   working_directory: ~/repo
#   docker:
#     - image: circleci/node:8.11
# version: 2
# jobs:
#   checkout_code:
#     <<: *defaults
#     steps:
#       - restore_cache:
#           keys:
#             - source-{{ .Branch }}-{{ .Revision }}
#             - source-{{ .Branch }}-
#             - source-

#       - checkout

#       - save_cache:
#           key: source-{{ .Branch }}-{{ .Revision }}
#           paths:
#             - "~/repo"
#   install:
#     <<: *defaults
#     steps:
#       - restore_cache:
#           key: source-{{ .Branch }}-{{ .Revision }}
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: "Yarn install"
#           command: yarn install
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - node_modules
#   test:
#     <<: *defaults
#     steps:
#       - restore_cache:
#           key: source-{{ .Branch }}-{{ .Revision }}
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: "Test"
#           command: npm run test
#   build:
#     <<: *defaults
#     steps:
#       - restore_cache:
#           key: source-{{ .Branch }}-{{ .Revision }}
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: "Build app"
#           command: npm run build
#       - persist_to_workspace:
#           root: ~/repo
#           paths:
#             - dist
#             - package.json
#   deploy:
#     <<: *defaults
#     steps:
#       - attach_workspace:
#           at: ~/repo
#       - run: sudo apt-get update && sudo apt-get install -y python-dev
#       - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
#       - run: sudo python get-pip.py
#       - run: sudo pip install awscli --upgrade
#       - run: aws --version
#       - run: aws s3 ls
#       - run: 
#           name: "Deploy to S3"
#           command:
#             aws s3 sync ~/repo s3://skand-admin-dashboard --acl public-read
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - checkout_code
#       - install:
#           requires:
#             - checkout_code
#       - test:
#           requires:
#             - install
#       - build:
#           requires:
#             - install
#       - deploy:
#           requires:
#             - test
#             - build