defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11

version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    <<: *defaults
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm build
  deploy:
    <<: *defaults
    steps:
      - run: 
          name: "Deploy to S3"
          command:
            aws s3 sync ~/repo s3://skand-admin-dashboard --acl public-read

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy

# defaults: &defaults
#   working_directory: ~/repo
#   docker:
#     - image: circleci/node:8.11
# version: 2
# jobs:
#   checkout_code:
#     <<: *defaults
#     steps:
#       - restore_cache:
#           keys:
#             - source-{{ .Branch }}-{{ .Revision }}
#             - source-{{ .Branch }}-
#             - source-

#       - checkout

#       - save_cache:
#           key: source-{{ .Branch }}-{{ .Revision }}
#           paths:
#             - "~/repo"
#   install:
#     <<: *defaults
#     steps:
#       - restore_cache:
#           key: source-{{ .Branch }}-{{ .Revision }}
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: "Yarn install"
#           command: yarn install
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - node_modules
#   test:
#     <<: *defaults
#     steps:
#       - restore_cache:
#           key: source-{{ .Branch }}-{{ .Revision }}
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: "Test"
#           command: npm run test
#   build:
#     <<: *defaults
#     steps:
#       - restore_cache:
#           key: source-{{ .Branch }}-{{ .Revision }}
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: "Build app"
#           command: npm run build
#       - persist_to_workspace:
#           root: ~/repo
#           paths:
#             - dist
#             - package.json
#   deploy:
#     <<: *defaults
#     steps:
#       - attach_workspace:
#           at: ~/repo
#       - run: sudo apt-get update && sudo apt-get install -y python-dev
#       - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
#       - run: sudo python get-pip.py
#       - run: sudo pip install awscli --upgrade
#       - run: aws --version
#       - run: aws s3 ls
#       - run: 
#           name: "Deploy to S3"
#           command:
#             aws s3 sync ~/repo s3://skand-admin-dashboard --acl public-read
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - checkout_code
#       - install:
#           requires:
#             - checkout_code
#       - test:
#           requires:
#             - install
#       - build:
#           requires:
#             - install
#       - deploy:
#           requires:
#             - test
#             - build